### PR TITLE
FIX Issue 1269: CHANGE css hard coded colors to vars

### LINKED ISSUE #1269: [TINY] Some colors are hard coded instead of using grist-var-colors.
### Describe the current behavior

*Start a new document* background on the new page is hard coded to `#DCF4EB` . For `custom.css` to properly apply it would be better to set it to `--grist-color-selection-opaque`.

### Steps to reproduce

1. overload --grist-color-selection-opaque in `custom.css` with some distinctive color.
2. see that it don't apply for *Start a new document background*

### Describe the expected behavior

The base color overloaded in custom.css must apply to every element in grist.

### Where have you encountered this bug?

- [ ] On [docs.getgrist.com](https://docs.getgrist.com)
- [X] On a self-hosted instance

### Instance information (when self-hosting only)

* Grist instance:
  * Version: 1.2.0
  * URL (if it's OK for you to share it): grist.numerique.gouv.fr
  * Installation mode: kubernetes
  * Architecture: multi-workers

* Browser name, version and platforms on which you could reproduce the bug: firefox 130.0.1

### PR DESCRIPTION
**Pull request by hexaltation**
## Context

Some color values are hard coded instead of using grist colors vars 

## Proposed solution

Changing hard coded color values by grist colors variables

## Related issues

Fixes #1269 

## Has this been tested?

- [x] yes by building a image with custom css overload locally 
- [ ] 👍 yes, I added tests to the test suite
- [ ] 💭 no, because this PR is a draft and still needs work
- [ ] 🙅 no, because this is not relevant here
- [ ] 🙋 no, because I need help 

## Screenshot

2024-10-16_11-33_with custom css

### CODE REVIEW

File: app/client/ui2018/cssVars.ts [hunk 1]
```diff
@@ -111,7 +111,7 @@ export const vars = {
   labelTextBg:    new CustomProp('label-text-bg', '#FFFFFF'),
   labelActiveBg:  new CustomProp('label-active-bg', '#F0F0F0'),
 
-  controlMargin:  new CustomProp('normal-margin', '2px'),
+  controlMargin:  new CustomProp('normal-margin',  '2px'),
```
Comment (fflorent) [inline app/client/ui2018/cssVars.ts:114]: Extra space not required.

```suggestion
  controlMargin:  new CustomProp('normal-margin', '2px'),
```

**Review by fflorent — APPROVED** [review]
Just an unnecessary extra space to remove, otherwise LGTM

File: app/client/ui2018/cssVars.ts (hunk 1 above)
Comment (fflorent) [reply app/client/ui2018/cssVars.ts:114]: OK then, you may resolve this conversation :)

**Review by berhalak — APPROVED** [review]
Thanks @hexaltation!
