### PR TITLE
SCIM: fix the member types for /Roles

### LINKED ISSUE #1989: SCIM: Confusion of member types in GET /Roles endpoints
### Describe the current behavior

When querying the `GET /api/scim/v2/Roles` endpoint, we see members of the Roles.

When a role is inherited (for example the roles of a doc inside a workspace), we expect the members of the Role of the document to include Roles of the workspace.

But we see Groups. For example:
```json
    {
      "schemas": [
        "urn:ietf:params:scim:schemas:Grist:1.0:Role"
      ],
      "id": "2300",
      "meta": {
        "resourceType": "Role",
        "location": "/api/scim/v2/Roles/2300"
      },
      "displayName": "viewers",
      "members": [
        {
          "value": "336",
          "display": "viewers",
          "$ref": "/api/scim/v2/Groups/336",
          "type": "Group"
        }
      ],
    }
```

### Describe the expected behavior

We should see this list of members instead:
```json
      [
        {
          "value": "336",
          "display": "viewers",
          "$ref": "/api/scim/v2/Roles/336",
          "type": "Role"
        }
      ]
```

### Where have you encountered this bug?

- [ ] On [docs.getgrist.com](https://docs.getgrist.com)
- [x] On a self-hosted instance

### Instance information (when self-hosting only)

_No response_

### PR DESCRIPTION
**Pull request by fflorent**
## Context

Quoting #1989:

When querying the `GET /api/scim/v2/Roles` endpoint, we see members of the Roles.

When a role is inherited (for example the roles of a doc inside a workspace), we expect the members of the Role of the document to include Roles of the workspace.

But we see Groups. For example:
```json
    {
      "schemas": [
        "urn:ietf:params:scim:schemas:Grist:1.0:Role"
      ],
      "id": "2300",
      "meta": {
        "resourceType": "Role",
        "location": "/api/scim/v2/Roles/2300"
      },
      "displayName": "viewers",
      "members": [
        {
          "value": "336",
          "display": "viewers",
          "$ref": "/api/scim/v2/Groups/336",
          "type": "Group"
        }
      ],
    }
```

## Proposed solution

Also the schema of the Role's "members" attribute had to be updated, as it accepts members that are Users, Groups but also other Roles.

Roles can contain other Roles members with the inheritance, for example when a doc inherits of all the roles from its workspace: then the owners Role of the doc contains the "owners" Role of the workspace.

## Related issues

Fixes #1989

## Has this been tested?

- [x] 👍 yes, I added tests to the test suite
- [ ] 💭 no, because this PR is a draft and still needs work
- [ ] 🙅 no, because this is not relevant here
- [ ] 🙋 no, because I need help

### CODE REVIEW

File: app/server/lib/scim/v2/roles/SCIMMYRoleSchema.ts [hunk 1]
```diff
@@ -15,10 +15,33 @@ export class SCIMMYRoleSchema extends SCIMMY.Types.Schema {
   private static _definition = (function() {
     // Clone the Groups schema definition
     return new SchemaDefinition(
-      "Role", "urn:ietf:params:scim:schemas:Grist:1.0:Role", "Role in Grist (Owner)", [
+      "Role", "urn:ietf:params:scim:schemas:Grist:1.0:Role", "Role in Grist", [
         new Attribute("string", "displayName", {
           mutable: false, direction: "out" }),
-        SCIMMY.Schemas.Group.definition.attribute("members"),
+        // SCIMMY.Schemas.Group.definition.attribute("members"),
```
Comment (paulfitz) [inline app/server/lib/scim/v2/roles/SCIMMYRoleSchema.ts]: Is this line needed?

Comment (fflorent) [reply app/server/lib/scim/v2/roles/SCIMMYRoleSchema.ts]: Oops, thanks!

**Comment by fflorent** [comment]
The error looks related to this fix:
https://github.com/gristlabs/grist-help/pull/593/files
