### PR TITLE
Webhook: Do not fetch table with formulas if no webhook is enabled

### LINKED ISSUE #799: Deadlock with webhooks?
Some of our users have their document *stuck* (i.e. the users wait forever until someone `force-reload`s it) after working a bit on it. 

I could reproduce the issue locally, and I could nearly reproduce the issue: the document is stuck immediately at the load. It's 100% satisfying (I would expect the production to behave the same), but it appears that the webhook are guilty here, even when all of them are disabled.

My understanding of the issue is the following (do not hesitate to challenge or correct me):
1. At the document initialization, the webhooks are triggered (we trigger a [calculate formula](https://github.com/gristlabs/grist-core/blob/main/app/server/lib/ActiveDoc.ts#L2344) which [triggers the webhooks](https://github.com/gristlabs/grist-core/blob/65757854eae163720a585aecb2e1ee0074f237c4/app/server/lib/Sharing.ts#L339)) and waits until that's done;
2. In order to trigger the webhooks, [the documents are loaded](https://github.com/gristlabs/grist-core/blob/65757854eae163720a585aecb2e1ee0074f237c4/app/server/lib/Triggers.ts#L212), waiting for the formulas (the meaning of the boolean flag for the `fetchQuery` method);
3. Waiting for the formulas involves waiting for the document initialization(cf [`wantsFull`](https://github.com/gristlabs/grist-core/blob/main/app/server/lib/ActiveDoc.ts#L999-L1000) and the call to [`waitForInitialization()`](https://github.com/gristlabs/grist-core/blob/65757854eae163720a585aecb2e1ee0074f237c4/app/server/lib/ActiveDoc.ts#L1008C18-L1008C39)) ⇒ deadlock;

I cannot share yet a document to reproduce the issue. I wonder if just creating a simple table with formulas in it and a webhook wouldn't be enough for that. If you request it, I can attempt to create one.

PS: Also maybe worth to mention: our production use GVisor, but the python engine is Pyodide when  running locally. I wonder if that's not the explanation of the slight difference between what I got and what happens to our users. Still not 100% satisfied by my analysis.

### PR DESCRIPTION
**Pull request by fflorent**
# Context

Some of our users have their document stuck at some point. My analysis is that it is related to webhooks, even when they are disabled.

For more details, see  #799

# Proposed solution

This solution does not fix  #799, but at least I propose to not fetching table data when all of the webhooks are disabled (unless I misunderstand something, that is unnecessary). With that patch, I could manage to make the document work on my local machine.

### CODE REVIEW

**Comment by alexmojaki** [comment]
I think it'd be better to filter at this line: `const triggersByTableRef = _.groupBy(triggersTable.getRecords(), "tableRef");`. And then the `if (!trigger.enabled) {` check can be removed.

**Comment by fflorent** [comment]
@alexmojaki Done!

File: app/server/lib/Triggers.ts [hunk 1]
```diff
@@ -174,7 +174,10 @@ export class DocTriggers {
     const triggersTable = docData.getMetaTable("_grist_Triggers");
     const getTableId = docData.getMetaTable("_grist_Tables").getRowPropFunc("tableId");
 
-    const triggersByTableRef = _.groupBy(triggersTable.getRecords(), "tableRef");
+    const triggersByTableRef = _.pickBy(
+      _.groupBy(triggersTable.getRecords(), "tableRef"),
+      (tables) => tables.some((t) => t.enabled)
+    );
```
Comment (alexmojaki) [inline app/server/lib/Triggers.ts:180]:
```suggestion
    const triggersByTableRef = _.groupBy(triggersTable.getRecords().filter(t => t.enabled), "tableRef");
```

**Comment by alexmojaki** [comment]
Please remove `if (!trigger.enabled) {` further down the file, and add a test somewhere that non-enabled webhooks aren't triggered (I can't see one, finding an existing test that fails if nothing checks `enabled` would work too).

**Comment by fflorent** [comment]
Done! (also if I am right for the condition removed)

> add a test somewhere that non-enabled webhooks aren't triggered (I can't see one, finding an existing test that fails if nothing checks enabled would work too).

You talk about nbrowser tests? (I only found them for webhooks)

**Comment by alexmojaki** [comment]
As well as the nbrowser tests, there's some in the DocApi tests.

File: test/server/lib/DocApi.ts [hunk 2]
```diff
@@ -3969,34 +3967,44 @@ function testDocApi() {
...
-        const webhookIds: Record<string, string> = {};
-        for (const eventTypes of [
-          ["add"],
-          ["update"],
-          ["add", "update"],
-        ]) {
+        for (const eventTypes of eventTypesSet) {
           const {data, status} = await axios.post(
-            `${serverUrl}/api/docs/${docId}/tables/Table1/_subscribe`,
-            {eventTypes, url: `${serving.url}/${eventTypes}`, isReadyColumn: "B"}, chimpy
```
Comment (fflorent) [inline test/server/lib/DocApi.ts:3994]: Happy new year @alexmojaki! :tada: 

I could manage to introduce some tests as requested… However, it takes advantage of this deprecated endpoint API.

Is it OK? 
Or may I convert this piece of code to rather use `POST /webhooks`? (if it's relevant for this endpoint to be called in the `describe('table endpoints'` section)

File: test/server/lib/DocApi.ts [hunk 3]
```diff
@@ -3969,34 +3968,40 @@ function testDocApi() {
         }
       });
 
+      async function createWebhooks({docId, tableId, eventTypesSet, isReadyColumn, enabled}:
+        {docId: string, tableId: string, eventTypesSet: string[][], isReadyColumn: string, enabled?: boolean}
+      ) {
+        const subscribeResponses = [];
+        const webhookIds: Record<string, string> = {};
```
Comment (alexmojaki) [inline test/server/lib/DocApi.ts:3975]: Please move these down to where they're used.

File: test/server/lib/DocApi.ts [hunk 4]
```diff
@@ -4100,6 +4105,26 @@ function testDocApi() {
...
       });
+
+      it("doesn't send trigger webhook that has been disabled", async function () {
+        // Create a test document.
+        const ws1 = (await userApi.getOrgWorkspaces('current'))[0].id;
+        const docId = await userApi.newDoc({name: 'testdoc'}, ws1);
+        const doc = userApi.getDocAPI(docId);
+
+        await createWebhooks({
+          docId, tableId: 'Table1', isReadyColumn: "B", eventTypesSet: [ ["add"] ], enabled: false
```
Comment (alexmojaki) [inline test/server/lib/DocApi.ts:4116]: Please add a similar but enabled webhook and confirm that there is an event for the enabled webhook. I'm worried that this test could pass for the wrong reasons, e.g. because of a race condition.

File: test/server/lib/DocApi.ts (hunk 2 above)
Comment (alexmojaki) [reply test/server/lib/DocApi.ts:3994]: I think what you've done looks fine.

**Review by alexmojaki — CHANGES_REQUESTED** [review]
Please confirm that the test passes with the old version of Triggers.ts and fails if both checks for `enabled` are removed.

**Comment by alexmojaki** [comment]
And happy new year to you too!

**Comment by fflorent** [comment]
Thanks for your review! I have taken into account your remarks.

> Please confirm that the test passes with the old version of Triggers.ts 

It does

> and fails if both checks for enabled are removed.

I understand here that you want me to remove 2 conditions. It fails if I remove this condition:

https://github.com/gristlabs/grist-core/blob/de13a2fd7a1391af70a840a1640f4a46c03843c6/app/server/lib/Triggers.ts#L548-L549

I don't see another one though.

File: test/server/lib/DocApi.ts (hunk 4 above)
Comment (fflorent) [reply test/server/lib/DocApi.ts]: I have made 2 different tests with the same codebase. Is it fine or you would like this in a same single test run?

**Comment by alexmojaki** [comment]
I meant that it should fail if neither the original check nor the new check you've replaced it with is present. I assume you're saying that it fails if the original check is removed from the original Triggers.ts file, which is equivalent. So I think we're good.
