### PR TITLE
Fix deadlock with webhooks on document load #799

### LINKED ISSUE #799: Deadlock with webhooks?
Some of our users have their document *stuck* (i.e. the users wait forever until someone `force-reload`s it) after working a bit on it. 

I could reproduce the issue locally, and I could nearly reproduce the issue: the document is stuck immediately at the load. It's 100% satisfying (I would expect the production to behave the same), but it appears that the webhook are guilty here, even when all of them are disabled.

My understanding of the issue is the following (do not hesitate to challenge or correct me):
1. At the document initialization, the webhooks are triggered (we trigger a [calculate formula](https://github.com/gristlabs/grist-core/blob/main/app/server/lib/ActiveDoc.ts#L2344) which [triggers the webhooks](https://github.com/gristlabs/grist-core/blob/65757854eae163720a585aecb2e1ee0074f237c4/app/server/lib/Sharing.ts#L339)) and waits until that's done;
2. In order to trigger the webhooks, [the documents are loaded](https://github.com/gristlabs/grist-core/blob/65757854eae163720a585aecb2e1ee0074f237c4/app/server/lib/Triggers.ts#L212), waiting for the formulas (the meaning of the boolean flag for the `fetchQuery` method);
3. Waiting for the formulas involves waiting for the document initialization(cf [`wantsFull`](https://github.com/gristlabs/grist-core/blob/main/app/server/lib/ActiveDoc.ts#L999-L1000) and the call to [`waitForInitialization()`](https://github.com/gristlabs/grist-core/blob/65757854eae163720a585aecb2e1ee0074f237c4/app/server/lib/ActiveDoc.ts#L1008C18-L1008C39)) ⇒ deadlock;

I cannot share yet a document to reproduce the issue. I wonder if just creating a simple table with formulas in it and a webhook wouldn't be enough for that. If you request it, I can attempt to create one.

PS: Also maybe worth to mention: our production use GVisor, but the python engine is Pyodide when  running locally. I wonder if that's not the explanation of the slight difference between what I got and what happens to our users. Still not 100% satisfied by my analysis.

### PR DESCRIPTION
**Pull request by fflorent**
# Context

Resolves #799 

# Proposed solution

This deadlock occurs because we trigger the webhooks even on Calculate action. As suggested by @alexmojaki, webhooks can discard these actions.

### CODE REVIEW

File: app/server/lib/Sharing.ts [hunk 1]
```diff
@@ -336,7 +337,9 @@ export class Sharing {
       }
       await this._activeDoc.processActionBundle(ownActionBundle);
 
-      const actionSummary = await this._activeDoc.handleTriggers(localActionBundle);
+      const actionSummary = !isCalculate ?
```
Comment (alexmojaki) [inline app/server/lib/Sharing.ts:340]: `isCalculate` has become misleading and should probably be renamed as it includes other actions. I don't think it should be used here, the exception should probably exist only for the actual Calculate action. In particular it would make sense to trigger webhooks after a RespondToRequests.

File: app/server/lib/Sharing.ts [hunk 2]
```diff
@@ -336,7 +337,9 @@ export class Sharing {
...
+        await this._activeDoc.handleTriggers(localActionBundle) :
+        createEmptyActionSummary();
```
Comment (alexmojaki) [inline app/server/lib/Sharing.ts:342]: This should use `summarizeAction` like Triggers.ts does, no reason to assume the summary should be empty.

File: app/server/lib/Sharing.ts (hunk 1 above)
Comment (fflorent) [reply app/server/lib/Sharing.ts:341]: Thanks for the hint!

File: app/server/lib/Sharing.ts [hunk 3]
```diff
@@ -336,7 +337,10 @@ export class Sharing {
       }
       await this._activeDoc.processActionBundle(ownActionBundle);
 
-      const actionSummary = await this._activeDoc.handleTriggers(localActionBundle);
+      const isCalculate = userActions.length === 1 && userActions[0][0] === 'Calculate';
+      const actionSummary = !isCalculate ?
```
Comment (alexmojaki) [inline app/server/lib/Sharing.ts:341]: Please add a comment to explain the conditional here to future readers.

Comment (fflorent) [reply app/server/lib/Sharing.ts]: Done. I also renamed the variable so it reflects what I believe it represents (I understand that we only discard the webhook trigger with a single Calculate action).

**Comment by alexmojaki** [comment]
Thanks!
